# Generated by Django 5.0.2 on 2024-03-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.AddField(
            model_name='order',
            name='book_name',
            field=models.CharField(default='The Alchemist', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=299, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
