# Generated by Django 5.0.2 on 2024-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_book_order_book_name_order_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod',
            field=models.BooleanField(default=True),
        ),
    ]
