# Generated by Django 5.0.2 on 2024-02-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cover_page', models.BinaryField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.seller')),
            ],
        ),
    ]
