# Generated by Django 5.0.2 on 2024-02-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bname',
            new_name='BNAME',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='b_id',
            new_name='B_ID',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover_page',
            new_name='COVER_PAGE',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='PRICE',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='seller',
            new_name='SELLER_ID',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_id',
            new_name='SELLER_ID',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_name',
            new_name='SELLER_NAME',
        ),
    ]
