# Generated by Django 5.0.2 on 2024-02-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_seller_landing_seller_landing_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing_book',
            old_name='SELLER_ID',
            new_name='SELLER_ID_id',
        ),
    ]
