# Generated by Django 5.0.2 on 2024-03-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_landing_book_cover_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_book',
            name='IMAGE',
            field=models.CharField(default='Alchemist.jpg', max_length=30),
        ),
    ]
